name = "Nexus"
uuid = "e9ec3f1b-eb74-4459-9c53-c196fe7664ef"
authors = ["kreikrei <kreitonstrs@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[compat]
Lazy = "0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
